site_name: 'YAP'
nav:
theme: 'readthedocs'
use_directory_urls: true
markdown_extensions:
    - smarty
    - toc:
        permalink: true
    - sane_lists
plugins:
  - search
  - awesome-pages:
      filename: .index
