package:
  name: yap4py
  version: 1.8.0

requirements:
  ignore_prefix_files:
    - startup.yss
  build:
    - cmake
    - swig
    - gmp
    - readline
    - python
    - r
    - notebook
    - pkgconfig
    - make
run:
    - python
    - pythonlab
    - readline
    - gmp
    - r
    - notebook
about:
    home: http://www.github.com/vscosta/yap-6.3.git
    license: LGPL2
    license_family: LGPL
    summary: Prolog System

source:
  path: ..
